import type { Metadata } from "next";
import type { ReactNode } from "react";
import Image from "next/image";
import "./mentoria.css";

const whatsapp = "https://api.whatsapp.com/send?phone=5583981330155&text=Eu%20vi%20sua%20mentoria%20e%20tenho%20interesse";

const audience = ["Quer entrar na tecnologia", "Estuda assuntos desconectados", "Ainda não sabe qual área seguir", "Tem dificuldade em transformar cursos em prática", "Quer construir projetos", "Precisa organizar os próximos passos", "Quer conhecer o mercado antes de se especializar"];
const cycle = [["Avaliar", "Entendemos seu momento atual."], ["Definir", "Escolhemos o objetivo do ciclo."], ["Planejar", "Organizamos estudos e entregas."], ["Executar", "Você transforma plano em prática."], ["Acompanhar", "Corrigimos obstáculos no caminho."], ["Revisar", "Analisamos o que foi desenvolvido."], ["Evoluir", "Definimos o próximo ciclo."]];
const benefits = [["Diagnóstico inicial", "Entendimento do seu momento, experiência, objetivos, interesses e disponibilidade."], ["Trilha personalizada", "Uma sequência de estudos construída conforme o seu objetivo — e não uma grade pronta."], ["Ciclo mensal", "Um objetivo principal por período, com direção clara e espaço para ajustar a rota."], ["Plano de ação", "Entregas e estudos objetivos para avançar entre um encontro e outro."], ["Até 4 encontros", "Encontros individuais usados conforme a necessidade e a finalidade de cada ciclo."], ["Materiais complementares", "Cursos, vídeos, documentação, exercícios e referências escolhidos para você."], ["Projetos práticos", "O aprendizado se transforma em entregas reais sempre que possível."], ["Revisão de evolução", "Analisamos os resultados e decidimos juntos o próximo ciclo."]];
const faqs = [["Preciso saber programar?", "Não. A mentoria pode começar antes da escolha de uma linguagem ou área."], ["Preciso saber qual área quero seguir?", "Não. Descobrir uma direção possível faz parte do diagnóstico inicial."], ["Existe uma trilha igual para todo mundo?", "Não. A trilha é ajustada ao seu objetivo, momento e disponibilidade."], ["São quatro reuniões obrigatórias?", "Há até quatro encontros por ciclo, distribuídos conforme a necessidade."], ["A mentoria fornece cursos?", "Os materiais são recomendados conforme a trilha; o foco é combinar referência e prática."], ["Vou conseguir um emprego depois da mentoria?", "A mentoria não promete contratação. Ela ajuda a construir repertório, projetos e clareza para os próximos passos."]];

export const metadata: Metadata = {
  title: "Mentoria individual em tecnologia",
  description: "Mentoria individual para encontrar direção, construir uma trilha personalizada e evoluir na tecnologia com prática.",
  alternates: { canonical: "/mentoria" },
  openGraph: { type: "website", locale: "pt_BR", title: "Mentoria Godeguesi", description: "Direção, prática e acompanhamento individual em tecnologia.", url: "/mentoria", images: [{ url: "https://www.godeguesi.com.br/visual/og_image_mentoria_godeguesi_v2.png", alt: "Mentoria Godeguesi" }] },
  twitter: { card: "summary_large_image", title: "Mentoria Godeguesi", description: "Direção, prática e acompanhamento individual em tecnologia.", images: ["https://www.godeguesi.com.br/visual/og_image_mentoria_godeguesi_v2.png"] },
};

function Section({ eyebrow, title, children, id }: { eyebrow: string; title: ReactNode; children: ReactNode; id?: string }) {
  return <section className="mentoria-section" id={id}><div className="mentoria-wrap"><p className="mentoria-eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</div></section>;
}

export default function MentoriaPage() {
  return <main className="mentoria" id="inicio">
    <header className="mentoria-header"><a href="#inicio" className="mentoria-brand"><Image src="/visual/mentoria/tg-mark.svg" alt="" width={36} height={36}/><span>Mentoria<br/>Godeguesi</span></a><nav aria-label="Navegação principal"><a href="#como-funciona">Como funciona</a><a href="#investimento">Investimento</a><a href="#faq">Dúvidas</a></nav><a className="mentoria-button mentoria-button-small" href={whatsapp}>Conversar <span>↗</span></a></header>
    <section className="mentoria-hero"><div className="mentoria-wrap"><p className="mentoria-eyebrow">Mentoria individual em tecnologia</p><h1>Encontre seu caminho na tecnologia <em>sem precisar descobrir tudo sozinho.</em></h1><p className="mentoria-lead">Entrar em tecnologia não deveria significar fazer dezenas de cursos sem saber onde eles vão levar você. Entenda onde está, defina onde quer chegar e construa um caminho possível.</p><div className="mentoria-actions"><a className="mentoria-button" href={whatsapp}>Quero conhecer a mentoria <span>↗</span></a><a className="mentoria-text-link" href="#como-funciona">Ver como funciona ↓</a></div><p className="mentoria-note"><b>01</b><span><strong>Não é um curso.</strong> É acompanhamento individual, organizado em ciclos mensais de evolução.</span></p></div></section>
    <section className="mentoria-intro"><div className="mentoria-wrap mentoria-split"><Image src="/visual/mentoria/thiago-godeguesi.png" alt="Thiago Godeguesi, mentor de tecnologia" width={1024} height={1536}/><div><p className="mentoria-eyebrow">Seu mentor</p><h2>Thiago Godeguesi</h2><p>Profissional de tecnologia com experiência em desenvolvimento de sistemas, engenharia de dados, cloud, arquitetura, automação e construção de produtos digitais.</p></div></div></section>
    <Section eyebrow="Para quem é" title={<>Para quem está começando — ou ainda tentando descobrir <em>por onde começar.</em></>}><p className="mentoria-copy">Você não precisa chegar sabendo qual linguagem aprender ou qual profissão seguir. Parte da mentoria é justamente descobrir isso junto com o mentor.</p><ul className="mentoria-checks">{audience.map(item => <li key={item}>✓ {item}</li>)}</ul></Section>
    <Section eyebrow="Direção antes de conteúdo" title={<>Primeiro entendemos você. <em>Depois construímos o caminho.</em></>}><p className="mentoria-copy">A mentoria começa pelo seu momento atual, objetivo, disponibilidade, forma de aprender e interesses. A trilha nasce desse diagnóstico.</p><div className="mentoria-areas">{["Backend", "Frontend", "Dados", "Cloud", "Inteligência Artificial", "DevOps", "Automação"].map(area => <span key={area}>{area}</span>)}<strong>Sua trilha<br/>Personalizada</strong></div></Section>
    <Section id="como-funciona" eyebrow="Como funciona" title={<>Um ciclo mensal de <em>evolução.</em></>}><p className="mentoria-copy">Cada mês tem um objetivo. Cada encontro tem uma finalidade. A proposta não é preencher horas — é fazer você avançar.</p><div className="mentoria-steps">{cycle.map(([title, text], index) => <article key={title}><b>{String(index + 1).padStart(2, "0")}</b><h3>{title}</h3><p>{text}</p></article>)}</div><p className="mentoria-callout"><strong>Até 4 encontros individuais</strong> por ciclo, distribuídos conforme a necessidade.</p></Section>
    <Section eyebrow="O que você recebe" title={<>Estrutura para avançar. <em>Liberdade para ajustar.</em></>}><div className="mentoria-benefits">{benefits.map(([title, text], index) => <article key={title}><b>{String(index + 1).padStart(2, "0")}</b><h3>{title}</h3><p>{text}</p></article>)}</div></Section>
    <section className="mentoria-image-section"><Image src="/visual/mentoria/technology-growth.png" alt="Caminho tecnológico em evolução, conectando dados, nuvem e desenvolvimento" width={1536} height={1024}/><div className="mentoria-wrap"><p className="mentoria-eyebrow">Aprender fazendo</p><h2>Curso sozinho não cria <em>experiência.</em></h2><p className="mentoria-copy">O objetivo é construir gradualmente coisas que você consiga explicar, demonstrar e evoluir.</p><div className="mentoria-examples"><span><b>Git</b> → repositório real</span><span><b>Python</b> → aplicação</span><span><b>Banco de dados</b> → projeto</span><span><b>API</b> → aplicação prática</span></div></div></section>
    <Section eyebrow="Uma trilha que evolui com você" title="Você não precisa decidir agora o que fará pelos próximos cinco anos."><div className="mentoria-number-list">{["A trilha pode mudar.", "O ritmo pode mudar.", "Os materiais podem mudar.", "Até a área pode mudar."].map((text, index) => <p key={text}><b>{String(index + 1).padStart(2, "0")}</b>{text}</p>)}</div><p className="mentoria-copy">A direção existe para <strong>orientar</strong>, não para prender.</p></Section>
    <Section eyebrow="Exemplo de ciclo" title={<>Mês 1 — <em>Fundamentos e direção</em></>}><p className="mentoria-copy">Revisamos o que você conseguiu desenvolver e definimos o próximo ciclo.</p><ol className="mentoria-timeline">{["Diagnóstico", "Área inicial de exploração", "Ambiente de estudos", "Git e GitHub", "Fundamentos técnicos", "Primeira entrega prática", "Revisão"].map((item, index) => <li key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</li>)}</ol></Section>
    <Section eyebrow="Terminou antes?" title={<>Você terminou antes do planejado? <em>Ótimo.</em></>}><p className="mentoria-copy">Não é necessário esperar o próximo ciclo. Podemos adicionar exercícios, aprofundamento, materiais, desafios ou preparar os próximos conhecimentos.</p><p className="mentoria-copy">A ideia não é limitar sua velocidade. É manter uma sequência coerente.</p></Section>
    <Section eyebrow="Por que trabalhar em ciclos?" title={<>A própria tecnologia nos ensina a <em>evoluir por etapas.</em></>}><p className="mentoria-copy">Assim como na tecnologia trabalhamos com Sprints — períodos definidos para executar um conjunto de tarefas e avaliar os resultados —, na mentoria cada ciclo tem objetivos claros, execução, acompanhamento e revisão.</p><div className="mentoria-flow">{["Planejar", "Executar", "Revisar", "Ajustar", "Evoluir"].map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div><p className="mentoria-copy">Você não planeja a carreira inteira de uma vez. Planeja o próximo ciclo, aprende com o resultado e decide o próximo passo.</p></Section>
    <Section id="investimento" eyebrow="Investimento" title="Clareza para o próximo passo."><p className="mentoria-copy">Uma parceria de 12 meses, individual e construída ao redor do seu momento.</p><div className="mentoria-price"><p>Mentoria individual</p><div><sup>R$</sup> <strong>995,11</strong></div><p>Start inicial</p><hr/><p><strong>Depois, 11 mensalidades de R$ 499,99.</strong></p><ul>{["Diagnóstico e planejamento individual", "Trilha personalizada", "Até 4 encontros", "Acompanhamento e materiais", "Próximas entregas e revisão do ciclo"].map(item => <li key={item}>✓ {item}</li>)}</ul><p>Investimento total para 12 meses: R$ 6.495,00.</p><p>Caso prefira fechar o pacote anual, o investimento será de R$ 5.500,00 à vista.</p><a className="mentoria-button" href={whatsapp}>Quero conversar sobre a mentoria <span>↗</span></a></div></Section>
    <Section id="faq" eyebrow="Perguntas frequentes" title={<>Antes de começar, <em>vale saber.</em></>}>{faqs.map(([question, answer], index) => <details className="mentoria-faq" key={question}><summary><b>{String(index + 1).padStart(2, "0")}</b>{question}<span>+</span></summary><p>{answer}</p></details>)}</Section>
    <section className="mentoria-closing"><div className="mentoria-wrap"><p className="mentoria-eyebrow">Seu próximo ciclo pode começar agora</p><h2>Você não precisa aprender tudo. <em>Precisa descobrir qual é o próximo passo.</em></h2><p className="mentoria-copy">Se existe informação demais e direção de menos, podemos construir esse caminho juntos.</p><a className="mentoria-button" href={whatsapp}>Quero conhecer a mentoria <span>↗</span></a></div></section>
    <footer className="mentoria-footer"><a href="#inicio" className="mentoria-brand"><Image src="/visual/mentoria/tg-mark.svg" alt="" width={36} height={36}/><span>Mentoria<br/>Godeguesi</span></a><p>© 2026 Thiago Godeguesi</p><a href="https://godeguesi.com.br">godeguesi.com.br ↗</a></footer>
  </main>;
}
